# Generated by Django 5.1.6 on 2025-02-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FunFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('source', models.CharField(max_length=100)),
                ('source_url', models.URLField()),
                ('language', models.CharField(choices=[('he', 'Hebrew'), ('en', 'English')], max_length=2)),
            ],
        ),
    ]
