# Generated by Django 4.2.19 on 2025-02-16 13:39

from django.db import migrations
from django.core.management import call_command

def run_seed_command(apps, schema_editor):
    call_command('seed_db') 

class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_course_alter_quote_year_student_enrollment'),
    ]

    operations = [
        migrations.RunPython(run_seed_command)
    ]


# python manage.py makemigrations quotes
# python manage.py migrate